name: flutter_web_portfolio_2025
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^10.1.0+1
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5
  flutter_bloc: ^9.1.1
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  get_it: ^8.0.0
  injectable: ^2.5.0
  path_provider: ^2.1.4
  json_annotation: ^4.9.0
  freezed: ^3.1.0
  connectivity: ^3.0.6
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^3.1.0
  url_launcher: ^6.3.2
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  bcrypt: ^1.1.3
  uuid: ^4.5.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^10.1.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/