name: Build & Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Enable web
        run: flutter config --enable-web

      - name: Get deps
        run: flutter pub get

      - name: Build web
        run: flutter build web --release

      - name: Prepare publish dir
        run: |
          touch build/web/.nojekyll
          cp build/web/index.html build/web/404.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          keep_files: false
          verbose: true