name: Build & Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Enable web support
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Fix base href for GitHub Pages (use relative)
        run: |
          # Replace absolute base with relative so assets load correctly on repo pages
          sed -i 's|<base href=\"/\">|<base href=\"./\">|g' build/web/index.html

      - name: Prepare publish directory
        run: |
          # Prevent Jekyll processing and enable client-side routing fallback
          touch build/web/.nojekyll
          cp build/web/index.html build/web/404.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          keep_files: false
          verbose: true