name: Build & Deploy Flutter Web to GitHub Pages (prototype/portfolio)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          cache: true
      
      - name: Enable web support
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get

      # Build Flutter web with correct base-href
      - name: Build Flutter Web
        run: flutter build web --release --base-href /prototype/portfolio/

      - name: Prepare publish directory
        run: |
          # Prevent Jekyll processing
          touch build/web/.nojekyll
          # Add fallback for SPA refresh
          cp build/web/index.html build/web/404.html
          # (Optional) Add CNAME only if you want vyakran.com root handling
          echo 'vyakran.com' > build/web/CNAME

      # Deploy only to the subdirectory prototype/portfolio
      - name: Deploy to gh-pages/prototype/portfolio
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          destination_dir: prototype/portfolio
          keep_files: true
          verbose: true